デプロイスクリプト修正及び環境変数の設定
pokumon-nft/pokumon-nft pull request #12
Opened 2022-01-19 09:17 UTC by YWBIZ

2022-01-19 09:19 UTC, YWBIZ commented
@tommy19970714   
先日に本番デプロイ時に修正したコードを反映しましたので、確認お願いします。
※その他環境変数の置き換えなど軽微な修正も加えてますので、個別に注釈付けます。

2022-01-19 09:21 UTC, YWBIZ commented on contracts/PokumonNFT.sol
>      function getLevel() public view returns (uint256) {
public指定した変数は内部でgetterが付与される(※今回の場合だとstatus())ようで、こちらの関数不要でした。

2022-01-19 09:24 UTC, YWBIZ commented on hardhat.config.ts
>    },
開発環境で動かすようにテストネットの設定追加しました。

2022-01-19 09:24 UTC, YWBIZ commented on package.json
>    },
デプロイ用にnpmスクリプト作成しました。

2022-01-19 09:26 UTC, YWBIZ commented on scripts/dev/mint-nft.ts
> +async function mintNFT(
開発用のミントのスクリプトですが、ipfsやfirestoreへのアップロードなしの簡易版になります。

2022-01-20 12:15 UTC, tommy19970714 requested changes
開発用のデプロイスクリプトは、環境変数で分けるようにしてほしいです。

2022-01-20 12:15 UTC, tommy19970714 commented on .gitignore
> +.openzeppelin/
このcacheって不必要なのでしょうかね？
コントラクトをアップデートした履歴が残っているような気がして、これがなくてもアップデートが可能なのでしょうか？調べる必要があるかもです

2022-01-20 12:15 UTC, tommy19970714 commented on contracts/PokumonNFT.sol
> +    function buy(uint256 _tokenId) public payable {
これ逆だったのですね

2022-01-20 12:15 UTC, tommy19970714 commented on contracts/PokumonNFT.sol
>      function getLevel() public view returns (uint256) {
なるほど。不要ということで承知しました

2022-01-20 12:15 UTC, tommy19970714 commented on hardhat.config.ts
>    },
両方あったほうがいいですね。追加ありがとうございます。
PRIVATE KEYもDEVかPRODCUTIONか分けられたほうがいいですかね？

2022-01-20 12:15 UTC, tommy19970714 commented on package.json
>    },
わかりやすくなって良いですね！
READMEも書き換えてもらえると助かります。

2022-01-20 12:15 UTC, tommy19970714 commented on scripts/dev/mint-nft.ts
> +async function mintNFT(
開発と本番の切り分けはファイルで分けずに、環境変数で分けるようにしてほしいです。

2022-01-20 12:17 UTC, tommy19970714 commented
確認ですが、public指定した変数はgetterはつきますがsetterはないですよね？

2022-01-20 14:16 UTC, YWBIZ commented
> 確認ですが、public指定した変数はgetterはつきますがsetterはないですよね？

@tommy19970714
setterは自動付与されないみたいです。
書き込み系はバグの温床になるから、実行権限付与して明示的に定義させる仕様にしているんでしょうね。

2022-01-20 15:49 UTC, tommy19970714 commented
フロントのcontract.tsでawait contract.getStatus()としていますが、いまはgetStatusというmethodはないですよね？publicだと勝手にmethodが作られるイメージですか？

2022-01-20 16:32 UTC, YWBIZ commented
> @YWBIZ フロントのcontract.tsでawait contract.getStatus()としていますが、いまはgetStatusというmethodはないですよね？publicだと勝手にmethodが作られるイメージですか？

こちらのプルリクで上記メソッドを消したので、フロント側は後ほど修正かける予定です。
publicの変数に対しては同名でgetter関数が付与されるようです。

2022-01-20 16:34 UTC, YWBIZ commented
@tommy19970714 
先程Issueで挙げたデータ構造の修正と合わせて、フロント側も修正しますので、最終的に下記のようなコードになるかと思います。
`contract.pokumons(tokenId).status`

2022-01-22 08:36 UTC, YWBIZ commented on .gitignore
> +.openzeppelin/
@tommy19970714   
確かにコントラクトをアップグレードする際にコントラクトIDを指定する必要があるので、履歴を残しておいた方がいいですね。ignoreから外しておきました。

2022-01-22 08:55 UTC, YWBIZ commented
@tommy19970714 
本番と開発で環境変数を分けるやり方ですが、dotenvのオプションで読み込み対象のenvファイルを指定できるようでしたので、npmスクリプトで制御する方針としました。以下、実行手順になります。

- cross-env(環境変数を設定できるライブラリ)を用いて、本番環境でNODE_ENVという変数を設定(※開発は設定しない)
```
"mint-nft-testnet": "yarn run clean && npx hardhat run --network ropsten scripts/mint-nft.ts",
"mint-nft-mainnet": "yarn run clean && cross-env NODE_ENV=production npx hardhat run --network polygon scripts/mint-nft.ts"
```

- hardhat.config.tsの中で、set-env.tsの下記関数を呼び出し、本番用及び開発用のenvファイルを読み込む
```
export const setEnv = () => {
  const ENV_NAME =
    process.env.NODE_ENV === "production" ? ".env.production" : ".env";
  const ENV_PATH = path.join(__dirname, ENV_NAME);
  dotenv.config({ path: ENV_PATH });
};
```

2022-01-22 08:59 UTC, YWBIZ commented
環境変数のファイルに関して、各ローカルに.envと.env.productionを設定する形となります。  
上記の方針で問題無ければ、README.mdなども更新しますので、確認及びコメントよろしくお願いします。

2022-01-22 15:38 UTC, tommy19970714 approved these changes
LGTM!!

2022-01-23 08:39 UTC, merged